global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3003']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3004']

